-- Create Franchises Table
create table if not exists public.franchises (
  id text primary key,
  name text not null,
  description text,
  backdrop_path text,
  type text,
  value integer default 0,
  is_custom boolean default false,
  content jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Franchises
alter table public.franchises enable row level security;

-- Policies for Franchises
create policy "Public can view franchises"
  on public.franchises for select
  using (true);

create policy "Public can insert/update franchises"
  on public.franchises for all
  using (true)
  with check (true);

-- Create Users Table (Custom Auth)
create table if not exists public.users (
  username text primary key,
  password text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Users
alter table public.users enable row level security;

-- Policies for Users (Public for custom auth)
create policy "Public can view users"
  on public.users for select
  using (true);

create policy "Public can insert users"
  on public.users for insert
  with check (true);

create policy "Public can update users"
  on public.users for update
  using (true);

create policy "Public can delete users"
  on public.users for delete
  using (true);

-- Create Watch History Table
create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  username text references public.users(username) on delete cascade not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  media_id integer not null,
  title text not null,
  poster_path text,
  timestamp integer default 0,
  duration integer default 0,
  progress integer default 0,
  season_number integer,
  episode_number integer,
  episode_title text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(username, media_id, media_type)
);

-- Create My List Table
create table if not exists public.my_list (
  id bigint generated by default as identity primary key,
  username text references public.users(username) on delete cascade not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  media_id integer not null,
  title text not null,
  poster_path text,
  release_date text,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(username, media_id, media_type)
);

-- Enable RLS
alter table public.watch_history enable row level security;
alter table public.my_list enable row level security;

-- Policies for Watch History (Public for custom auth)
create policy "Public can view watch history"
  on public.watch_history for select
  using (true);

create policy "Public can insert watch history"
  on public.watch_history for insert
  with check (true);

create policy "Public can update watch history"
  on public.watch_history for update
  using (true);

create policy "Public can delete watch history"
  on public.watch_history for delete
  using (true);

-- Policies for My List (Public for custom auth)
create policy "Public can view list"
  on public.my_list for select
  using (true);

create policy "Public can insert list"
  on public.my_list for insert
  with check (true);

create policy "Public can delete list"
  on public.my_list for delete
  using (true);

-- Create Friendships Table
create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester text references public.users(username) on delete cascade not null,
  addressee text references public.users(username) on delete cascade not null,
  status text not null check (status in ('pending', 'accepted', 'blocked')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(requester, addressee)
);

-- Enable RLS for Friendships
alter table public.friendships enable row level security;

-- Policies for Friendships
create policy "Users can view their own friendships"
  on public.friendships for select
  using (auth.uid()::text = requester or auth.uid()::text = addressee or true); -- Public for now since we use custom auth and no real auth.uid() mapping yet

-- Note: Since we are using custom auth (username/password stored in public.users) and not Supabase Auth,
-- we cannot rely on auth.uid(). We will make these public for now and handle logic in the app/API.
-- Ideally, we should migrate to Supabase Auth or implement a custom RLS function.
-- For this prototype, we'll allow public access but filter in the UI/API.

create policy "Public can insert friendships"
  on public.friendships for insert
  with check (true);

create policy "Public can update friendships"
  on public.friendships for update
  using (true);

create policy "Public can delete friendships"
  on public.friendships for delete
  using (true);

-- Watch Parties Table
create table if not exists public.watch_parties (
  id uuid default gen_random_uuid() primary key,
  host_id text references public.users(username) on delete cascade not null,
  media_type text not null,
  media_id integer not null,
  status text default 'active',
  video_timestamp float default 0,
  is_playing boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Watch Party Participants Table
create table if not exists public.watch_party_participants (
  id bigint generated by default as identity primary key,
  party_id uuid references public.watch_parties(id) on delete cascade not null,
  user_id text references public.users(username) on delete cascade not null,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(party_id, user_id)
);

-- Watch Party Messages Table
create table if not exists public.watch_party_messages (
  id bigint generated by default as identity primary key,
  party_id uuid references public.watch_parties(id) on delete cascade not null,
  user_id text references public.users(username) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.watch_parties enable row level security;
alter table public.watch_party_participants enable row level security;
alter table public.watch_party_messages enable row level security;

-- Public Policies (for prototype)
create policy "Public can view parties" on public.watch_parties for select using (true);
create policy "Public can insert parties" on public.watch_parties for insert with check (true);
create policy "Public can update parties" on public.watch_parties for update using (true);

create policy "Public can view participants" on public.watch_party_participants for select using (true);
create policy "Public can insert participants" on public.watch_party_participants for insert with check (true);
create policy "Public can delete participants" on public.watch_party_participants for delete using (true);

create policy "Public can view messages" on public.watch_party_messages for select using (true);
create policy "Public can insert messages" on public.watch_party_messages for insert with check (true);
